version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      - run:
          name: Run unit tests
          command: |
            go test ./...

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
