version: 2.1

orbs:
  buildpulse: workshop64/buildpulse@0.7

jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      - run: mkdir -p /tmp/test-results

      - run:
          name: Run unit tests
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile /tmp/test-results/gotestsum-report.xml -- $PACKAGE_NAMES

      - buildpulse/upload:
          path: /tmp/test-results
          account-id: 68192324 # Replace this value with your BuildPulse account ID
          repository-id: 237812225 # Replace this value with your BuildPulse repository ID

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
